### ISSUE TITLE
Design: Chapter navigation

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#86] opened 2021-02-27 14:45 UTC
[Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=971%3A0)

**Comment by mjcarsjens** [comment] 2021-04-09 11:16
duplicate of #71

**Closed** 2021-04-24 08:33 UTC
Labels: duplicate
